POST https://juliaapi.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Júlia",
    "email": "borssatojulia@gmail.com",
    "password": "123456789"
}
###########################################
POST https://juliaapi.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "borssatojulia@gmail.com",
    "password": "123456789"
}